Update README.md
SuperCoder7979/ecotones pull request #16
Opened 2021-07-18 03:53 UTC by DestinyTheGreat

This is up-to-date with Ecotones right now, as far as I am aware.

2021-07-18 16:57 UTC, StefanJanssen95 reviewed
> Ecotones is perfectly stable and won't crash

That's a bold claim to make

2021-07-21 16:17 UTC, TehcJS requested changes

2021-07-21 16:17 UTC, TehcJS commented on README.md
> +Ecotones is highly in development and things will change with or without notice! Be warned that updating may cause chunk borders or other anomalies. However, Ecotones is perfectly stable and won't cr
```diff
- However, Ecotones is perfectly stable and won't crash.
```
you are making false statements of fact

2021-07-27 19:58 UTC, SuperCoder7979 commented
I ended up doing this manually. Thank you though :)

2021-07-27 19:58 UTC, closed without merging